### PR TITLE
I216 reporting an incident for a visit doesn t work

### LINKED ISSUE #216: Reporting an incident for a visit doesn't work
## Basic Information
When submitting the Report Incident Form, the incident is not being added to the notes like "Register Vet Concern" is.

## Describe the solution you'd like
Fix bug

The relevant information of the Report Incident Form is to be appended to the end of the notes.

### PR DESCRIPTION
**Pull request by RadioArsenic**
## Change Summary
Now appends incidents to the visit notes in the same manner as vet concerns.

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [x] The pull request title has an issue number
- [x] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
**[Is there anything in particular in the review that I should be aware of?]**

# Related Issue

- Resolve #216

### CODE REVIEW

**Comment by RadioArsenic** [comment]
WIP until tomorrow, don't have time today to fix conflicts

**Comment by skyheat** [comment]
Only appends incidents done locally.

I have 3 incident reports in the Firestore but it only displays one of them (the one done locally). Register vet concerns works as expected where all vet concerns are in the ntoes.

image
image

**Comment by RadioArsenic** [comment]
> 

Correct me I'm wrong but I believe that's because both the incidents and vet concerns are appended to the notes when they are created, so it doesn't know that those old incidents exist, which shouldn't be an issue as all the actual incidents will be reported in the future and the past incidents were all just us testing things.

**Comment by skyheat** [comment]
Sorry, wasn't really very clear. What I'm trying to say is that vet concerns persist over 'branches' while incidents don't so far. i.e. If i submit a vet concern in the main branch, it'll also show up in this branch. But not for incidents.

**Comment by RadioArsenic** [comment]
Still confused, is that not just because the main branch hasn't been updated to append incidents to notes when they're created? Which is the whole point of this PR? (Vet concerns already does that on main which is why it carries across to here).
Or are you saying that incidents you report in this branch don't show up in the notes on main? Which it very much should already be doing.

**Comment by skyheat** [comment]
> Still confused, is that not just because the main branch hasn't been updated to append incidents to notes when they're created? Which is the whole point of this PR? (Vet concerns already does that on main which is why it carries across to here). Or are you saying that incidents you report in this branch don't show up in the notes on main?

I pretty much thought that if I submitted an incident on the deployment (poops.vercel.app), it **wont** append it to the notes on main but **would** show up in the notes of this branch. I thought that the notes was just read from the Firestore but I may be wrong.

**Review by skyheat — APPROVED** [review]

**Pull request merged**
