### PR TITLE
I147 create a stat page for admin

### LINKED ISSUE #147: Create a stat page for admin
**Is your feature request related to a problem? Please describe.**
Admins need a page to see how their users are doing.

**Describe the solution you'd like**
Create a stats page for the admin based on the design made in the figma #135 .
The page should consist of:
- Per volunteer:
  - Total # visits, minutes, kms over the period
  - Average number of visits, minutes, kms per week
  - Average number of clients

**Additional context**
You dont have to worry about Firebase integration or restricting to access to this page.
This will be created in another issue.

### PR DESCRIPTION
**Pull request by Techno-UWA**
# Change Summary
#147 create a stat page for admin

### Purpose of issue
A stats page for the Admin to view volunteer stats

### Pages
- Created admin folder in pages ->
- Inside admin folder in pages created stats page ->
- stats page: displays volunteer stats to the admin in form of a table

### Components
Created VolunteerStatsTable component which is the table component of the stats page

***NOTE: It currently only has dummy data and will need to be integrated with firebase in a future issue***

The stats table includes this data:
```typescript
const {
    voluteerCount,
    totalClientCount,
    totalCommuteDistance,
    totalVisitCount,
    totalWalkDistance,
    totalWalkTime,
    avgClientCount,
    avgCommuteDistance,
    avgVisitCount,
    avgWalkDistance,
    avgWalkTime
  }
```

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [X] The pull request title has an issue number
- [X] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
The stats table only uses dummy data so will need to be integrated with Firebase in a future issue
The table is not up to date with the figma but the plan is to update the figma based on what has been done for the stats table which I'll get to after submitting this pull request

# Related Issue

- Resolve #147

### CODE REVIEW

**Review by skyheat — APPROVED** [review]
Looks good!

**Review by skyheat — CHANGES_REQUESTED** [review]
Fix conflicts

**Comment by Techno-UWA** [comment]
> Fix conflicts

Ok I think they've been fixed now? I merged with main and removed any differences so there shouldn't be any merge conflicts or unnecessary changes now?

**Review by scratchclaggy — DISMISSED** [review]
LGTM :rocket:

**Review by skyheat — APPROVED** [review]

**Pull request merged**
