### PR TITLE
I57 requires user signin to access the pages

### LINKED ISSUE #57: Requires user signin to access the pages
## Basic Information

Description of the issue

- [ ] Redirect users to the login page if they are not signed in
- [ ] use next router

## Other Information

Potential scopes:

### PR DESCRIPTION
**Pull request by JakeLDev**
## Change Summary
Protected internal routes between pages by a login requirement, If user isn't logged in, they are redirected to the login page. If a user is logged in, and tries to access the login page, they are directed to the home page.

Features many additions from i24 and i25 as I merged with those branches in order to use the firebase code and the login page. However those branches are not yet ready to merge as we are still working on the login page.

## Other Information
Minor edits to each page must be done in order to keep the protection when new pages are added. Also added temporary logout button to profile page for error checking this feature

# Related Issue

- Resolve #57

### CODE REVIEW

**Review by skyheat — CHANGES_REQUESTED** [review]
Looks good!

Just minor issues such as unnecessary comments (eg. console.log()) should be deleted but otherwise good stuff!

**Review by JakeLDev — COMMENTED** [review]
Removed unnecessary comments and console logs

**Review by skyheat — CHANGES_REQUESTED** [review]
yarn.lock merge conflicts need to be fixed.

**Review by skyheat — APPROVED** [review]
Looks good!

**Pull request merged**
