### PR TITLE
I198 buttons disappear when notes are too long

### LINKED ISSUE #198: Buttons disappear when notes are too long
**Is your feature request related to a problem? Please describe.**
Unable to see the edit, vet concern and incident buttons when notes is too long

**Describe the solution you'd like**
Buttons shouldn't disappear. 

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by jordantgiang**
## Change Summary
**Fixed bug that caused the visit instance buttons to disappear if the "notes" were too big for the max-height.**

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [x] The pull request title has an issue number
- [x] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
**The "Edit" button was also moved to be contained in the same container as the "Report Incident" and "Register Vet Concern" buttons**

# Related Issue

- Resolve #198

### CODE REVIEW

**Review by scratchclaggy — APPROVED** [review]
Looks great, nice work! :rocket:

**Comment by scratchclaggy** [comment]
image

@jordantgiang @skyheat 

I made some tweaks with spacing and font weight how does this look now?

**Review by scratchclaggy — APPROVED** [review]
Looks good. If you're happy with the changes I made in the last commit go ahead and merge. :rocket:

**Review by skyheat — APPROVED** [review]
ez

**Pull request merged**
