### PR TITLE
i137 border added to secondary button

### LINKED ISSUE #137: Add a border to the secondary variant button
**Is your feature request related to a problem? Please describe.**
The secondary variant button with white background looks does not look like a button in the app

**Describe the solution you'd like**
Add a border to the button

### PR DESCRIPTION
**Pull request by Techno-UWA**
## Change Summary
#137 Components->UI: Secondary variant Button
Added Tailwind border class to Secondary variant of button

### Change Form

- [x] The pull request title has an issue number
- [x] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

# Related Issue

- Resolve #137

### CODE REVIEW

**Review by scratchclaggy — APPROVED** [review]
Looks good to me :rocket:

**Comment by NicholasChoong** [comment]
image
the button in the contact does not have border
Great job!

**Comment by Techno-UWA** [comment]
Yay! Can I merge now?

**Comment by Techno-UWA** [comment]
@NicholasChoong ?

**Comment by NicholasChoong** [comment]
yup.
i looked at the wrong issue

**Review by NicholasChoong — APPROVED** [review]

**Pull request merged**
